apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: pod
spec:
  serviceAccountName: cd-jenkins
  containers:
    - name: maven
      image: maven:3.3.9-jdk-8-alpine
      command:
        - cat
      tty: true
      volumeMounts:
        - name: m2
          mountPath: /root/.m2/repository
          readOnly: false
    - name: docker
      image: docker:19.03.1-dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""      
    - name: helm
      image: lachlanevenson/k8s-helm:v3.7.0
      command:
        - cat
      tty: true
  volumes:
    - name: m2
      persistentVolumeClaim:
        claimName: "jenkins-pvc"
        readOnly: false  
